package:
  format-version: "1.0.0"
  name: "bsp"
  type: "api"
  status: "production"
  required: false
  version: "v3.23.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.23.0"