package:
  format-version: "1.0.0"
  name: "bsp"
  type: "api"
  status: "production"
  required: false
  version: "v3.21.0-E1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0-E1"